name: first workflow
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
    build1:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Welcome User
          run: echo welcome to github actions

